### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by aqrln** [VanCoding/nix-prisma-utils#2]
x86-64 binaries are hardcoded in https://github.com/VanCoding/nix-prisma-utils/blob/main/prisma.nix#L18 and downloaded regardless of the architecture, so the wrong binaries are downloaded on ARM64:

```

Unable to require(`/nix/store/bwyq8jwfw4fn6wlm96hqzmfw52pad4jl-prisma-bin-efd2449663b3d73d637ea1fd226bafbcf45b3102/lib/libquery_engine.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
```

**Comment by VanCoding** [comment]
@aqrln Thanks for bringing this up. I've indeed only ever needed the x86_64 binaries for now. Supporting other platforms could get a bit ugly, because it would require specifying different hashes depending on the platform. But to start, maybe I can just make the platform configurable. If specifying the hashes starts getting a burden, I could also add a CLI that automates this.

**Comment by VanCoding** [comment]
@aqrln I've made a [commit](https://github.com/VanCoding/nix-prisma-utils/commit/3ac1367526066df3443bea291c70317b4433db95) that adds support for ARM64.

It automatically detects the platform based on the nixpkgs instance passed in, so you only have to pass in different hashes based on the platform. You can see in the tests how this could be done.

**Comment by aqrln** [comment]
Awesome, thank you! The binary targets for darwin don't look right, those should be just `darwin` or `darwin-arm64` without the openssl stuff, but other than that looks great!

**Comment by VanCoding** [comment]
@aqrln Ah, true. I wonder if prisma even uses openssl on darwin, an if yes, what version is assumed. I'll have to investigate this a bit further, but I'll probably only do it once someone requests darwin support.

**Comment by aqrln** [comment]
@VanCoding Prisma doesn't use OpenSSL on Darwin, or at least it shouldn't. We use OpenSSL indirectly via the `native-tls` crate which uses OpenSSL on Linux, Apple's `Security.framework` on Darwin and SChannel on Windows. If OpenSSL somehow ended up compiled in via transitive dependencies, it would be statically linked since that's the default behaviour of the `openssl-sys` crate.

You'd need `pkgs.darwin.apple_sdk.frameworks.Security` in `buildInputs` if you were to build Prisma engines with Nix, but you don't need anything special to run it. Moreover, the same Darwin binaries will always just work out of the box regardless of whether Nix is used or not, and no patching is required even in full Nix environment on Darwin. I'm not sure if you even could patch them the same way if you wanted: without checking, I'd assume that `patchelf` and `autoPatchelfHook` can only probably handle ELF binaries and not the Darwin Mach-O binaries.

So perhaps a more useful feature would be to automatically generate an empty shell hook and skip all of this logic if the current system is detected to be Darwin.

**Comment by aqrln** [comment]
> So perhaps a more useful feature would be to automatically generate an empty shell hook and skip all of this logic if the current system is detected to be Darwin.

But that can also be handled on the caller side perfectly fine:

```nix
devShells.default = nixpkgs.mkShell {
  shellHook = pkgs.lib.optionalString pkgs.stdenv.isLinux prisma.shellHook;
};
```

So maybe you could just not worry about Darwin at all actually.

**Comment by VanCoding** [comment]
> But that can also be handled on the caller side perfectly fine:

Yes, that's what we're currently doing.

The only use case I see for properly handling darwin in nix-prisma-utils is when you want to ship an application directly with nix to darwin, which I doubt anyone will do in the forseeable future. But for that case, it would be desirable if we'd still download the binaries with nix instead of npm, but then do not attempt to patch them at all.

**Comment by aqrln** [comment]
Yep, the ability to pre-download the binaries could certainly be useful.

**Comment by aqrln** [comment]
Tested, works like a charm, thank you!
