### ISSUE TITLE
Non-interactive environment

### ISSUE THREAD

**Issue by AThilenius** [VanCoding/nix-prisma-utils#4]
Hi @VanCoding, thank you so much for making this! I'm not sure this is the right place for this issue, so feel free to close it, I'm just hooping you've seen this before an possibly have a solution.

On NixOS with this flake (or any other way of installing Prisma) I get the following error when I run any interactive prisma command with `npx prisma ...`:
```
Error: Prisma Migrate has detected that the environment is non-interactive, which is not supported.
```

The chunk of code that checks for interactivity is [this](https://github.com/prisma/prisma/blob/main/packages/internals/src/utils/isInteractive.ts#L9) which happily passes on my system. I switched to standard Bash to make sure it wasn't something to do with NuShell as well. This is on Prisma `5.13.0` which appears to be the latest version.

It's a real show-stopper, as the `migrate dev` command seems to have zero way to bypass the non-interactive check, for which both https://github.com/prisma/prisma/issues/4669 and https://github.com/prisma/prisma/issues/7113 exist.

Really appreciate your time!

**Comment by VanCoding** [comment]
Hmm, I can't say that I didn't have that problem as well at some point, but I can't tell what made it go away or if it completely prevented me from using prisma. I'll have to check if prisma 5.13 got worse in that regard.

It'd be interesting what makes prisma think that the environment is non-interactive. If there's something we can do to work around this, then we can keep this issue open. If it's something that can only be solved by fixing prisma, then we should close it.

**Comment by AThilenius** [comment]
https://github.com/keystonejs/keystone/pull/8898 was merged last year. I haven't mapped out enough of Prisma's inner workings to know one way or another. The error certainly originated from JS, no node, but the "why" is still a mystery to me.

I need to setup a Proxmox machine anyway, I'll see if I can come up with a minimal NixOS config + project to repro the issue at least. That might also point me in the right direction of what's causing it.

**Comment by aqrln** [comment]
Hey @AThilenius — I highly doubt this is related to this flake, this sounds like a bug on our side, especially since you said yourself:

> or any other way of installing Prisma

Once you have a reproduction ready, could you please open an issue in https://github.com/prisma/prisma? Thank you  🙏

**Comment by AThilenius** [comment]
@aqrln Will do. I agree, though it is likely to be specific to Nix, so figured I would start with someone else I know is using Nix. I'll mark this closed and reference it when I have a repro built out. Appreciate the responses!
